---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: java-demoapp-arm64
  name: java-demoapp-arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: java-demoapp-arm64
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-demoapp-arm64
        app.kubernetes.io/part-of: java-demoapp
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - image: xxxxxxxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/javawebapp:latest-aarch64
          name: main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
