---
apiVersion: v1
kind: Service
metadata:
  name: java-demoapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: java-demoapp-x86
    # app.kubernetes.io/part-of: java-demoapp
